### ISSUE TITLE
Unresolved namespace prefix 'fab'

### ISSUE THREAD

**Issue by SharkFourSix** [hannesa2/FloatingActionButton#12]
The `fab:` prefix does not resolve in Android Studio. Replacing it with `app` fixes the issue.

**Comment by hannesa2** [comment]
Where ? Please share a screenshot.

On my side all is fine
![image](https://user-images.githubusercontent.com/3314607/82137949-b2883a80-981c-11ea-9ddb-47c5200f1fe3.png)

If the issue still exists, please reopen issue
