### ISSUE TITLE
Wrong behavior

### ISSUE THREAD

**Issue by AlvaroEstrada** [hannesa2/FloatingActionButton#4]
First of all, thank you for supporting this library. You've sincerely saved my life hehe.

I wanted to tell you a wrong behavior in the fab movement when there is a Snackbar present.

In my case, a fab executes a snackbar (under certain conditions). If being an active snackbar, I press the fab again, the button is hidden behind it.

In short, execute the downward movement even if a snackbar is present.

On the other hand, I would like to ask you the incorporation of being able to deactivate the behavior to remove it in some specific fab.

EDIT: The problem occurs when displaying 2 snackbars in a row before the fab returns to its position.

Thank you!

**Comment by hannesa2** [comment]
You are welcome.
If you have a suggestion (best as a pull request) I will apply it.
At least a running example demonstrate the issue would be very helpful (best as a pull request)
