### ISSUE TITLE
get menu drawable not working

### ISSUE THREAD

**Issue by freehussain** [hannesa2/FloatingActionButton#6]
hello,

i'm trying to chnage color for menu, it was wroking fine on version 2.0 but after update not working

here is my code line
DrawableCompat.setTint(speedDialView.menuIconView.drawable, config.headerColor)

kind regards

**Comment by hannesa2** [comment]
For me it's not exactly clear, what you want to do.
At least a running example, which demonstrate the issue would be very helpful (best as a pull request in the sample app).
This helps you to isolate the issue, and it helps me to see exactly what's happen

**Comment by freehussain** [comment]
hello,

simply, i want to change menu icon color by adding color tint, in version 2.0 i was using code below to change it and it was working

DrawableCompat.setTint(speedDialView.menuIconView.drawable, "#ffff")

now, after update to version 2.3.1 color not set and i menu icon keep the same

sorry for bad english :)

**Comment by hannesa2** [comment]
> DrawableCompat.setTint(speedDialView.menuIconView.drawable, "#ffff")

.. best as a pull request in the sample app

This helps **_you_** to isolate the issue, and it helps **_me_** to see exactly what's happen
