### ISSUE TITLE
Not really a fork of the original

### ISSUE THREAD

**Issue by nokite** [hannesa2/FloatingActionButton#63]
Since this repo is not technically a fork of the original one, it's harder to find it etc

Here's an example:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/2574061/188850173-65026f9b-9d31-4b0d-9b28-d49efda45e9a.png">

And here's this repo:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/2574061/188850417-95760140-7611-4efe-b152-326502124372.png">

If you use a tool like this, it's not listed:
https://techgaun.github.io/active-forks/index.html#Clans/FloatingActionButton

Would be nice to make it an actual fork.

**Comment by hannesa2** [comment]
This repository has no more original lines from dead upstream. 
Sometimes you have to accept that something is dead and something new appears.
I see no reason to put afford into this request. -sorry-
